name: Daily ICE API Download and Email Report

on:
  schedule:
    - cron: '00 22 * * 1-5'  # Runs Mon-Fri at 22:00 UTC (6:00 PM EDT)
  workflow_dispatch:        # Manual trigger option

jobs:
  run-ice-api:
    runs-on: ubuntu-latest

    env:
      SAVE_DIR: ${{ github.workspace }}/ICE_CLEARED_POWER
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run ICE API script
        run: python ice_auto.py
